---
name: Tests
on: push
jobs:
  test-python:
    strategy:
      fail-fast: false
      matrix:
        python:
          - '2.7'
          - '3.5'
          - '3.6'
          - '3.7'
          - '3.8'
    name: Python ${{ matrix.python }}
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: ${{ matrix.python }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Determine Python version
        run: |
          set -ex
          python --version
      - name: Install tox
        run: |
          set -ex
          pip install --user tox
      - name: Run tests
        shell: bash
        run: |
          set -ex
          tox -e "py${PYTHON_VERSION//.}"
